components:
  path: kubeflow/components
  components:
    - name: my_add
    - name: my_divide

pipelines:
  path: kubeflow/pipeline
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0YmNkZjBmZWJmNDRiOGRhZGQxZWIyOGM2MjhkYWYxIn0.eyJ1c2VybmFtZSI6ImRlZXBha2tvbmtpbWFsbGEiLCJyb2xlIjoiZGF0YXNjaWVudGlzdCxtbGUscGUiLCJkZXBsb3kiOmZhbHNlLCJleHAiOjQ4NjA4OTI0MjcsImlhdCI6MTYyMDg5MjQyNywiaXNzIjoiRGt1YmUifQ.ccP6ZB7YD50bUDrGshwz9ohiqI6hmqZa8vRbqAFefBGb-pXlik7OSOD5Su0wPtAxpVYD2fXaEKFlyTAoJ2D38S4OFCozl-AzPArgeHPJz_04qaDrov2U-X0M-B9cjXHH3EhzAVTDKyZaLQLj4cff69Dd3-HeHlx6xCYzOUYWzpqZqYNy9gnBL2a_TPht6te5t3ITqVuzlSOkW5a_93t8l8RU-QiFkYa5vyFZvYGibrxUAjdRYYUdB0u8THJnuZjlB4P5H_m7CN03p4RQUtxwtL0KZYErj52XKI5h562JfUHe9-ex5Z7iGtwqNuhOwXFtRAm_ZCinuh4j9C9-cxFT7w
  pipelines:
    - name: workflow.py
      run: true
